baseURL = "/"
languageCode = "id-ID"
# theme = "hello-friend"
paginate = 5
DefaultContentLanguage = "id"
# disquss
  disqusShortname = "bizantech"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "light"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  # showReadingTime = true

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  toc = false

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  rssFullText = true
  # rssImage = "image/url/here"
  enableEmoji = true
  
  Comments = true



[languages]
  [languages.id]
    title = "Bizantech"
    subtitle = "Tempat tulisan iseng"
    keywords = "Programming, Blog"
    copyright = ""
    menuMore = "Lainnya"
    writtenBy = "Ditulis oleh"
    readMore = "Baca selanjutnya"
    readOtherPosts = "Baca postingan lainnya"
    newerPosts = "Posting baru"
    olderPosts = "Posting lama"
    # minuteReadingTime = "min read"
    dateFormatSingle = "02-01-2006"
    dateFormatList = "02-01-2006"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""
    TableOfContent = "Daftar isi"

    [languages.id.params.logo]
      logoText = "Bizantech"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.id.menu]
      [[languages.id.menu.main]]
        identifier = "tentang"
        name = "Tentang"
        url = "/tentang"
      [[languages.id.menu.main]]
        identifier = "arsip"
        name = "Arsip"
        url = "/arsip"
